FROM node:22-bookworm-slim

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

ENV DATABASE_URL=mysql://root:root@localhost:3306/metricdash
RUN npm run prisma:generate
RUN npm run build

ENV NODE_ENV=production
EXPOSE 8800

CMD ["node", "build/start/index.js"]
